### ISSUE TITLE
Updating from 1.5.0 to 1.6.2 introduces virus in scan and blocks release

### ISSUE THREAD

**Issue by lhl2617** [jazz-soft/JZZ-midi-SMF#15]
See relevant issue here: https://github.com/lhl2617/VSLilyPond/issues/353

Are there any new binaries/dependencies used here that may be malicious/flagged as a FP?

**Comment by jazz-soft** [comment]
There are no binaries in jzz-midi-smf. Pure JavaScript.
Did you try if any other version from 1.5.1 to 1.6.1 work better?

**Comment by lhl2617** [comment]
Hey! Sorry for the late reply, swamped with work. I'll try a pure project installing jzz-midi-smf and let you know of my findings.

**Comment by lhl2617** [comment]
# Binary search for first offending version

## Repro method
```
mkdir XX 
cd XX
npm init
npm i jzz-midi-smf@X.X.X
cd ..
zip -r XXX.zip XXX
# upload to https://www.virustotal.com
```

## Versions:
- 1.6.2 ❌ https://www.virustotal.com/gui/file/6a7d20e3541425104907d9f7493d71543a1f2c03bcb053439da1dd8a35df16f6?nocache=1

- 1.6.1

- 1.6.0

- 1.5.9

- 1.5.8

- 1.5.7

- 1.5.6

- 1.5.5

- 1.5.4

- 1.5.3

- 1.5.2

- 1.5.1

- 1.5.0

**Comment by lhl2617** [comment]
Diff between 1.5.9 and 1.6.0: https://github.com/jazz-soft/JZZ-midi-SMF/compare/v1.5.9...v1.6.0

This seems really innocuous, any insight into what is happening?

**Comment by lhl2617** [comment]
Ah, 
![image](https://user-images.githubusercontent.com/33488131/134785163-90f62eca-d22e-4dd6-96de-954c4c4caeae.png)

This change (https://github.com/jazz-soft/JZZ-midi-SMF/commit/eef77e4969ed8cdcc23ad0378ac6dd9d914fb0d4) might have been the culprit! Test files were added onto the npm package. Any motivation for this?

**Comment by jazz-soft** [comment]
The virus scan does not like one of the MIDI files in the test directory (9.mid).
I'll remove it.

**Comment by jazz-soft** [comment]
A new version has been released!
Thanks a lot for debugging!

**Comment by lhl2617** [comment]
Thanks so much for this!!
