### ISSUE TITLE
Can't load any midis. 

### ISSUE THREAD

**Issue by wolfy01** [jazz-soft/JZZ-midi-SMF#16]
Here is an example with 0.mid:
```
/workspace/nodejs-midiplayer/node_modules/jzz/javascript/JZZ.js:1605
  function _throw(x) { throw RangeError('Bad MIDI value: ' + x); }
                             ^

RangeError: Bad MIDI value: MThd`MTrk>ÿ
4-Byte VLQÿhttps://jazz-soft.netÿKThis file has 4-byte VLQ delta times. Technically, it's a valid MIDI file.
ÿYou must hear a C-Major scale.`<@`>@`@@`A@`C@`E@`G@`H@ÿ
Thank you!ÿ/
```
Another example with a different midi:
```
/workspace/nodejs-midiplayer/node_modules/jzz/javascript/JZZ.js:1605
  function _throw(x) { throw RangeError('Bad MIDI value: ' + x); }
                             ^

RangeError: Bad MIDI value: MThdàMTrk,WÿÿYúÿQ¢_°yÀ°d
```
Theres more after that `RangeError`, but its just a bunch of midi data. I loaded the midi just like the examples have shown, with fs.

**Comment by jazz-soft** [comment]
Thanks for the notice!
Could you please attach these MIDI files?

**Comment by jazz-soft** [comment]
Strange...
I don't see any issues when I open 0.mid during the "npm test". Can it be that your copy is corrupted?
I'll take a look at your other file.

**Comment by jazz-soft** [comment]
Which OS are you on? Does `npm test` work for you?

**Comment by wolfy01** [comment]
> Which OS are you on? Does `npm test` work for you?

`yarn run test` (Since I use yarn) works for me.

I was on linux. I tested on windows and had the same result, am I doing this correctly?: 
```js
const JZZ = require("jzz");
require("jzz-midi-smf")(JZZ);

fs.readFile("./midis/0.mid", "binary", (err, data) => {
    if (err) console.log(err);

    let smf = new JZZ.MIDI.smf(data);
    let midiPlayer = smf.player();

    midiPlayer.connect(output);
    midiPlayer.play();
});
```

**Comment by jazz-soft** [comment]
Change `let smf = new JZZ.MIDI.smf(data);` to `let smf = new JZZ.MIDI.SMF(data);` ;)

**Comment by jazz-soft** [comment]
Yes, I've just realized I have functions with similar names...
Need to think what to do about that...
