### ISSUE TITLE
Some other programs cannot find certain tracks

### ISSUE THREAD

**Issue by xp2-882030kgz010602** [jazz-soft/JZZ-midi-SMF#20]
Here's my code.
`var JZZ=require('jzz');
require('jzz-midi-smf')(JZZ);
var smf = new JZZ.MIDI.SMF(0, 96); // type 0, 96 ticks per quarter note
var trk = new JZZ.MIDI.SMF.MTrk();
smf.push(trk);
// add contents:
trk.add(0, JZZ.MIDI.smfSeqName('This is a sequence name'))
   .add(0, JZZ.MIDI.smfBPM(90)) // tempo 90 bpm
   .add(96, JZZ.MIDI.noteOn(0, 'D6', 127))
   .add(192, JZZ.MIDI.noteOff(0, 'D6'))
   .add(0, JZZ.MIDI.noteOn(0, 'E6', 127))
   .add(96, JZZ.MIDI.noteOff(0, 'E6'))
   .add(288, JZZ.MIDI.smfEndOfTrack());
var trk1 = new JZZ.MIDI.SMF.MTrk();
trk1.ch(2);
smf.push(trk1);
trk1.add(0, JZZ.MIDI.smfSeqName('This is another sequence name'))
   .add(96, JZZ.MIDI.noteOn(0, 'F6', 127))
   .add(192, JZZ.MIDI.noteOff(0, 'F6'))
   .add(0, JZZ.MIDI.noteOn(0, 'G6', 127))
   .add(96, JZZ.MIDI.noteOff(0, 'G6'))
   .add(288, JZZ.MIDI.smfEndOfTrack());
require('fs').writeFileSync('out.mid', smf.dump(), 'binary');`

If I open out.mid in MuseScore or in Domino, only the first track opens, which is strange, since Windows Media Player is able to find the other track.

**Comment by jazz-soft** [comment]
MuseScore and Domino may be confused because Type 0 MIDI files should contain only one track.
try to create a Type 1 MIDI file: `var smf = new JZZ.MIDI.SMF(1, 96);`

And please read the MIDI file specs!

And BTW, your both tracks play on the same MIDI channel, that may be not what you wanted to do.

**Comment by xp2-882030kgz010602** [comment]
I was using the wrong midi type ._.

**Comment by xp2-882030kgz010602** [comment]
Oh I missed your comment oops
